const CategoryType = {
    PERSONAL_BLOG: "BLOG_PERSONAL",
    PRODUCT_OR_SERVICE: "PRODUCTO_O_SERVICIO",
    ART: "ARTE",
    BAND_OR_MUSIC: "MUSICO_O_BANDA",
    RETAIL_PURCHASES_OR_SALES: "COMPRAS_O_VENTAS_MINORISTAS",
    HEALTH_OR_BEAUTY: "SALUD_O_BELLEZA",
    GROCERY_STORES: "TIENDAS_COMESTIBLES",
};

module.exports = { CategoryType }