name: Test and build image

on:
  push:
    branches: [ release, main]
  pull_request:
    branches: [ release, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          
      - name: Execute docker images
        run: docker-compose -f docker-compose.test.yml up -d --build
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install node dependencies
        run: npm ci
      - name: Run test
        run: npm test
        
  build-image:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the image
        run: |
          docker buildx build --push \
            --tag adrianc68/uvgram:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .

